# Interface
verbose = "info"
no_progress = true
cache = true
max_cache_age = "10m"

# Stealth
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0"
header = { "Accept" = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", "Accept-Language" = "en-US,en;q=0.5", "Accept-Encoding" = "gzip, deflate, br" }

# Prevent 'Too Many Open Files'
max_concurrency = 16

# Slower retries give rate-limited servers time to cool down
retry_wait_time = 5

# Check links inside `<code>` and `<pre>` blocks and Markdown code blocks
include_verbatim = true

# Check fragments in links
include_fragments = true

# Add 'Too many requests'
accept = ["100..=103", "200..=299", "429"]

# Be benevolent
max_retries = 5
timeout = 40

# Exclude
exclude = [
    "127\\.0\\.0\\.1:8000",
    "cz\\.pycon\\.org/20XX",

    # Anti-scraping protections
    "docs\\.google\\.com",
    "www\\.facebook\\.com",
    "www\\.nytimes\\.com",
    "accounts\\.google\\.com",
    "creativecommons\\.org/licenses/",
    "inkscape\\.org",
    "domena\\.cz",

    # Website implements the fragments wrong
    "cz\\.pycon\\.org/2016/speakers/talks/#"
]
