# The Pyvec board members in time
# The current board is first, previous boards are listed in descending order
# Each member has a `name`, `github`, and optionally a `roles` array

[[board]]
start_on = "2022-04-09"

[[board.members]]
name = "Barbora Drbohlavová"
github = "baradrb"
roles = ["chair"]

[[board.members]]
name = "Anežka Müller"
github = "anezkamll"

[[board.members]]
name = "Jan Javorek"
github = "honzajavorek"

[[board.members]]
name = "Jakub Vysoký"
github = "kvbik"

[[board.members]]
name = "Jan Čermák"
github = "sairon"
roles = ["treasurer"]



[[board]]
start_on = "2019-04-08"

[[board.members]]
name = "Martin Bílek"
github = "martinbilek"
roles = ["chair", "treasurer"]

[[board.members]]
name = "Aleš Zoulek"
github = "aleszoulek"

[[board.members]]
name = "Jan Javorek"
github = "honzajavorek"

[[board.members]]
name = "Jakub Vysoký"
github = "kvbik"

[[board.members]]
name = "Jiří Bartoň"
github = "whiskybar"



[[board]]
start_on = "2012-03-27"

[[board.members]]
name = "Martin Bílek"
github = "martinbilek"
roles = ["chair", "treasurer"]

[[board.members]]
name = "Aleš Zoulek"
github = "aleszoulek"

[[board.members]]
name = "Robin Gottfried"
github = "czervenka"

[[board.members]]
name = "Jan Král"
github = "honzakral"

[[board.members]]
name = "Jakub Vysoký"
github = "kvbik"

[[board.members]]
name = "Jiří Bartoň"
github = "whiskybar"

[[board.members]]
name = "Vítězslav Pliska"
github = "whit"
