name: Check Links
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 2"
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build documentation
        run: uv run sphinx-build -nWaE docs build
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: _build
          fail: false
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: broken links
